// Generated by CoffeeScript 1.6.3
var audio, bindButtonsEvents, createPlayerDOM, current_track, duration, info, initPlayer, loadTrack, nextTrack, next_song, play_button, play_pause, play_progress, play_section, previousTrack, previous_song, queryAlbum, removeTryButton, setProgress, title, toggleMusic, total_tracks, tracklist, try_button, updateProgress;

tracklist = total_tracks = current_track = audio = info = title = play_button = duration = play_progress = play_pause = next_song = previous_song = queryAlbum = function() {
  var $album_name, $performer, query_info, that;
  $album_name = $('#wrapper h1 > span')[0].innerText;
  $performer = $('#info span span.pl a')[0].innerText;
  that = this;
  that.innerText = "连接中";
  query_info = {
    type: "query",
    album: $album_name,
    performer: $performer
  };
  chrome.runtime.sendMessage(query_info, function(response) {
    if (response.status === "not found") {
      that.innerText = "虾米貌似目前还没有这张专辑";
    }
  });
};

createPlayerDOM = function() {
  var panel, player;
  player = document.createElement('div');
  player.id = "dx_player";
  info = document.createElement('div');
  info.id = "dx_info";
  title = document.createElement('div');
  title.id = "dx_title";
  audio = document.createElement('audio');
  duration = document.createElement('div');
  duration.id = "dx_duration";
  play_progress = document.createElement('div');
  play_progress.id = "dx_progress";
  duration.appendChild(play_progress);
  info.appendChild(title);
  info.appendChild(audio);
  info.appendChild(duration);
  panel = document.createElement('div');
  panel.id = "dx_panel";
  play_pause = document.createElement('div');
  play_pause.id = "dx_play_pause";
  play_pause.className = "dx_icon";
  next_song = document.createElement('div');
  next_song.id = "dx_next";
  next_song.className = "dx_icon";
  previous_song = document.createElement('div');
  previous_song.id = "dx_prev";
  previous_song.className = "dx_icon";
  panel.appendChild(play_pause);
  panel.appendChild(next_song);
  panel.appendChild(previous_song);
  player.appendChild(panel);
  player.appendChild(info);
  play_section.appendChild(player);
};

initPlayer = function(song_list) {
  tracklist = song_list;
  total_tracks = tracklist.length;
  return current_track = 0;
};

loadTrack = function(track_number) {
  var track;
  track = tracklist[track_number];
  audio.src = track.location;
  title.innerText = track.artist + " - " + track.title;
  audio.autoplay = true;
  audio.addEventListener("ended", nextTrack, false);
  return audio.addEventListener("timeupdate", updateProgress, false);
};

nextTrack = function() {
  setProgress(0);
  current_track++;
  if (current_track >= total_tracks) {
    current_track = 0;
  }
  return loadTrack(current_track);
};

previousTrack = function() {
  setProgress(0);
  current_track--;
  if (current_track <= -1) {
    current_track = total_tracks - 1;
  }
  return loadTrack(current_track);
};

updateProgress = function() {
  var bar_width, percent_played, width;
  width = parseInt($(duration).css('width'));
  percent_played = audio.currentTime / audio.duration;
  bar_width = Math.ceil(percent_played * width);
  return setProgress(bar_width);
};

toggleMusic = function() {
  if (audio.paused) {
    audio.play();
    return play_pause.innerText = "pause";
  } else {
    audio.pause();
    return play_pause.innerText = "play";
  }
};

setProgress = function(played_length) {
  return $(play_progress).css('width', played_length);
};

bindButtonsEvents = function() {
  play_pause.addEventListener("click", toggleMusic, false);
  next_song.addEventListener("click", nextTrack, false);
  return previous_song.addEventListener("click", previousTrack, false);
};

removeTryButton = function() {
  return $('#dx_try_button').remove();
};

play_section = document.createElement('div');

play_section.id = "dx_section";

try_button = document.createElement('a');

try_button.id = "dx_try_button";

try_button.innerText = "虾米试听";

play_section.appendChild(try_button);

$('.related_info').before(play_section);

$('#dx_try_button').on("click", queryAlbum);

chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
  if (request.status === "found") {
    removeTryButton();
    createPlayerDOM();
    initPlayer(request.songs);
    loadTrack(current_track);
    bindButtonsEvents();
  } else if (request.status === "not found") {
    $('#dx_try_button').innerText = "虾米貌似还没有人发布这张专辑";
  }
});
